# Notes_application

Если запускать python3 manage.py test запускаются тесты

Пробелемы:
1. Что-то странное с primary key
2. 
